config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "static#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :my do
    patch "/recipes/:id/remove_image", to: "recipes#remove_image", as: "recipe_image_remove"
    resources :recipes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: "recipe_ingredient"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients
  has_many :ingredients, through: "recipe_ingredient"
  accepts_nested_attributes_for :recipe_ingredients
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
  accepts_nested_attributes_for :ingredient
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/my/recipe_ingredients_controller.rb
class My::RecipeIngredientsController < ApplicationController
  def new
    @recipe_item = RecipeItem.new
    @recipe_item.build_ingredient
  end
end

app/controllers/my/recipes_controller.rb
class My::RecipesController < ApplicationController
  before_action :authenticate_user!
  def index
    @current_user = current_user
    @recipes = current_user.recipes
  end

  def new
    @recipe = Recipe.new
    @recipe.recipe_ingredients.build.build_ingredient
  end

  def create
    params[:recipe][:instructions] = params[:recipe][:instructions].to_json
    @recipe = current_user.recipes.build(recipe_params)
    build_recipe_ingredients

    if @recipe.save
      redirect_to :my_recipes
    else
      render "new"
    end
  end

  def edit
    @recipe = Recipe.find_by(id: params[:id])
    @instructions = JSON.parse(@recipe.instructions)
  end

  def update
    params[:recipe][:instructions] = params[:recipe][:instructions].to_json
    @recipe = Recipe.find_by(id: params[:id])

    if @recipe.update(recipe_params)
      redirect_to :my_recipes
    else
      render "edit"
    end
  end

  def show
    puts params
    @recipe = Recipe.find_by(id: params[:id])
    @instructions = JSON.parse(@recipe.instructions)
  end

  def destroy
    @recipe = Recipe.find_by(id: params[:id])
    @recipe.destroy

    redirect_to my_recipes_path
  end

  def remove_image
    @recipe = Recipe.find_by(id: params[:id])
    @recipe.photo.destroy
    @recipe.save
    render 'edit'
  end



  private
  def recipe_params
    params.require(:recipe).permit(:name, :description, :instructions, :total_time, :prep_time, :special_notes, :photo,
                                   recipe_ingredients_attributes: [:id, :amount, :unit_type, ingredient_attributes:[:name]])
  end

  def build_recipe_ingredients
    puts "build recipe ingredients"
    @recipe.recipe_ingredients.each do |recipe_item|
      recipe_item.ingredient = Ingredient.find_or_create_by(name: recipe_item.ingredient.name)
    end
  end


end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index

  end

  def new

  end

  def create

  end

  def show

  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/controllers/user/recipes_controller.rb
class User::RecipesController < ApplicationController
  before_action :authenticate_user!
  def index
    @current_user = current_user
    @recipes = current_user.recipes
  end

  def new
    @recipe = Recipe.new(user_id: current_user.id)
  end

  def create
    puts "inside create"
    @recipe = Recipe.new(recipe_params.merge(user_id: current_user.id))
    puts @recipe.inspect
    if @recipe.save
      redirect_to :user_recipes
    else
      puts "recipe failed"
      render 'new'
    end

  end

  def show

  end

  private
  def recipe_params
    params.require(:recipe).permit(:name, :description, :total_time, :prep_time, :special_notes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields",
            data: {id: id, fields: fields.gsub("\n", "")})
  end

end

app/helpers/my/recipe_ingredients_helper.rb
module My::RecipeIngredientsHelper
end

app/helpers/my/recipes_helper.rb
module My::RecipesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeSharer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid" >
    <%= render("shared/header") %>
    <div class= "col-md-12 main-content">
      <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/my/recipes/_recipe_ingredient_fields.html.erb
<div class="nested-fields row">
  <div class = "col-sm-2">
    <%= f.label :amount %>
    <%= f.number_field :amount, :step => 'any', :class => 'form-control' %>
  </div>
  <div class = "col-sm-2">
    <%= f.label :unit_type %>
    <%= f.text_field :unit_type, :class => 'form-control' %>
  </div>
    <div class = "col-sm-5">
      <% f.object.build_ingredient unless f.object.ingredient %>
      <%= f.fields_for :ingredient do |ff| %>
          <%= ff.label :name %>
          <%= ff.text_field :name, :class => 'form-control' %>
      <% end %>
    </div>
  <div class = "col-sm-2">
    <%= link_to_remove_association "Remove Ingredient", f %>
  </div>
</div>

app/views/my/recipes/edit.html.erb
<div class = "row">
  <%= form_for [:my, @recipe] do |f| %>
      <% if @recipe.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@recipe.errors.count, "error") %>
              prohibited this recipe from being saved:
            </h2>
            <ul>
              <% @recipe.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end%>
            </ul>
          </div>
      <%end %>
      <div class="form-group">

      </div>
      <div fieldset class="recipe_1">
        <div class = "row">
          <div class = "col-sm-6">
            <%= f.label :name %>:
            <%= f.text_field :name, :class => 'form-control' %>
          </div>
          <div class = "col-sm-3">
            <%= f.label :prep_time %>:
            <%= f.number_field :prep_time, :class => 'form-control' %>
            minutes
          </div>
          <div class = "col-sm-3">
            <%= f.label :total_time %>:
            <%= f.number_field :total_time, :class => 'form-control' %>
            minutes
          </div>
        </div>
        <div class = "row">
          <div class = "col-sm-12">
            <%= f.label :description %>:
            <%= f.text_field :description, :class => 'form-control' %>
          </div>
        </div>
      </div>
      <div fieldset class = "ingredients">
        <div id="ingredients">
          <label>Ingredients:</label>
          <%= f.fields_for :recipe_ingredients do |builder| %>
              <%= render 'recipe_ingredient_fields', f: builder %>

          <% end %>
          <div id="links">
            <%= link_to_add_association "Add Ingredient", f, :recipe_ingredients %><br/>
          </div>
        </div>
      </div>
      <div fieldset class = "instructions">
        <div class = "row">
          <div class = "col-sm-12">
            <%= f.label :instructions %>:


            <div class="nested-fields " id="recipe_steps">

              <% unless @instructions.nil? %>
                  <% @instructions.each do |instruction| %>
                      <%= text_field_tag 'recipe[instructions][]', instruction, class: 'instruction-field form-control' %>
                      <%= link_to "Remove Step", "javascript:void(0)", class: "remove_step" %>
                  <% end %>
              <% else %>
                  <%= text_field_tag 'recipe[instructions][]', nil, class: 'instruction-field form-control', placeholder: 'Type the first step' %>
                  <% end %><%= link_to "Remove Step", "javascript:void(0)", class: "remove_step" %>
            </div>
            <div class = "col-sm-3">

            </div></div>
        </div>
        <div class = "row">
          <div class = "col-sm-12">
            <%= link_to "Next Step", "javascript:void(0)", class: "new_step" %><br/>
          </div></div>
      </div>
      <div class = "row special-notes">
        <div class = "col-sm-12">
          <%= f.label :special_notes %>:
          <%= f.text_field :special_notes, :class => 'form-control' %>
        </div>
      </div>
      <div class = "row upload-image">
        <div class = "col-sm-12">
          <% if @recipe.photo.file? %>
          <%= image_tag @recipe.photo.url(:medium) %>
          <%= link_to 'Remove photo', my_recipe_image_remove_path(@recipe),
                      method: :patch,
                      class: "btn btn-danger" %>
          <% end %>
          <%= f.label :photo,'Upload new image' %>
          <%= f.file_field :photo %>
        </div>
      </div>


      <div class = "row">

        <div class = "col-sm-12">
          <%= f.button "Save Changes" %>
        </div>
      </div>
      <%= link_to 'view all recipes', my_recipes_path, class: 'new_recipe' %>
      </div>

  <% end %>

app/views/my/recipes/index.html.erb
Recipes
<%if @recipes.size > 0 %>

    <% @recipes.all.each do |recipe| %>

        <div class = "white user-item" >
          <a href = "<%=my_recipe_url(recipe.id)%>" class = "item-link">
            <div class = "item-box">
              <div class = "item-content">
                <div class = "item-desc">
                  <h5><%= recipe.name %></h5>
                </div>
              </div>
            </div>
          </a>
        </div>

    <% end %>

<% end %>
<%= link_to "Add a new recipe", :new_my_recipe %>

app/views/my/recipes/new.html.erb
<div class = "row">
  <%= form_for [:my, @recipe] do |f| %>
      <% if @recipe.errors.any? %>
          <div id="error_explanation">
          <h2>
            <%= pluralize(@recipe.errors.count, "error") %>
            prohibited this recipe from being saved:
          </h2>
          <ul>
            <% @recipe.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end%>
          </ul>
          </div>
      <%end %>
      <div class="form-group">

      </div>
      <div fieldset class="recipe_1">
        <div class = "row">
          <div class = "col-sm-6">
            <%= f.label :name %>:
            <%= f.text_field :name, :class => 'form-control' %>
          </div>
          <div class = "col-sm-3">
            <%= f.label :prep_time %>:
            <%= f.number_field :prep_time, :class => 'form-control' %>
            minutes
          </div>
          <div class = "col-sm-3">
            <%= f.label :total_time %>:
            <%= f.number_field :total_time, :class => 'form-control' %>
            minutes
          </div>
        </div>
        <div class = "row">
          <div class = "col-sm-12">
            <%= f.label :description %>:
            <%= f.text_field :description, :class => 'form-control' %>
          </div>
        </div>
      </div>
      <div fieldset class = "ingredients">
        <div id="ingredients">
          <label>Ingredients:</label>
          <%= f.fields_for :recipe_ingredients do |builder| %>
              <%= render 'recipe_ingredient_fields', f: builder %>
              <div id="links">
                <%= link_to_add_association "Add Ingredient", f, :recipe_ingredients %><br/>
              </div>
          <% end %>
        </div>
      </div>
      <div fieldset class = "instructions">
        <div class = "row">
          <div class = "col-sm-12">
          <%= f.label :instructions %>:


          <div class="nested-fields " id="recipe_steps">

            <% unless @instructions.nil? %>
                <% @instructions.each do |instruction| %>
                    <%= text_field_tag 'recipe[instructions][]', instruction, class: 'instruction-field form-control' %>
                <% end %>
            <% else %>
                <%= text_field_tag 'recipe[instructions][]', nil, class: 'instruction-field form-control', placeholder: 'Type the first step' %>
            <% end %><%= link_to "Remove Step", "javascript:void(0)", class: "remove_step" %>
          </div>
          <div class = "col-sm-3">

          </div></div>
        </div>
        <div class = "row">
        <div class = "col-sm-12">
        <%= link_to "Next Step", "javascript:void(0)", class: "new_step" %><br/>
        </div></div>
      </div>
      <div class = "row special-notes">
        <div class = "col-sm-12">
          <%= f.label :special_notes %>:
          <%= f.text_field :special_notes, :class => 'form-control' %>
        </div>
      </div>
      <div class = "row upload-image">
        <div class = "col-sm-12">
        <%= f.label :photo,'Upload new image' %>
        <%= f.file_field :photo %>
        </div>
      </div>


        <div class = "row">

          <div class = "col-sm-12">
          <%= f.button "Save" %>
          </div>
        </div>
      <%= link_to 'view all recipes', my_recipes_path, class: 'new_recipe' %>
      </div>

  <% end %>

</div>

app/views/my/recipes/show.html.erb
<%= @recipe.name %>
<% if @recipe.photo.file? %>
<%= image_tag @recipe.photo.url(:medium) %>
<% end %>
<p>
  <strong>Ingredients:</strong><br/>
  <% @recipe.recipe_ingredients.each do |recipe_item| %>
      <%= "#{recipe_item.amount} #{recipe_item.ingredient.name}" %><br/>
  <% end %>
</p>
<p>
  <strong>Instructions:</strong><br/>
  <% @instructions.each do |instruction| %>
      <%= instruction %><br/>
  <% end %>
</p>
<br/>
<%= link_to 'Back', my_recipes_path, class: "btn btn-default" %>
<%= link_to 'Edit', edit_my_recipe_path, class: "btn btn-default" %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#"><%=PROJECT_NAME%></a>
  <%if user_signed_in? %>
      <a class="navbar-brand" href="/users/sign_out" data-method="delete">Log out</a>
  <%else%>
      <a class="navbar-brand" href="/users/sign_in">Log in</a>
  <%end%>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/user/recipes/index.html.erb
Recipes
<%if @recipes.size > 0 %>

    <% @recipes.all.each do |recipe| %>

        <div class = "white user-item" >
          <a href = "<%=user_recipe_url(current_user.id, recipe.id)%>" class = "item-link">
            <div class = "item-box">
              <div class = "item-content">
                <div class = "item-desc">
                  <h5><%= recipe.name %></h5>
                </div>
              </div>
            </div>
          </a>
        </div>

    <% end %>

<% end %>
<%= link_to "Add a new recipe", :new_user_recipe %>

app/views/user/recipes/new.html.erb
<h3>Add a recipe</h3>
<%= form_for [:user, @recipe] do |f| %>
    <div class = "name">
      <%= f.label :name %>
      <%= f.text_field :name, class: "field" %>
    </div>
    <div class = "description">
      <%= f.label :description %>
      <%= f.text_field :description, class: "field"%>
    </div>
    <div class = "total_time">
      <%= f.label :total_time %>
      <%= f.number_field :total_time %> minutes
    </div>
    <div class = "prep_time">
      <%= f.label :prep_time %>
      <%= f.number_field :prep_time, class: "field"%> minutes
    </div>
    <div class = "special_notes">
      <%= f.label :special_notes %>
      <%= f.text_field :special_notes, class: "field"%>
    </div>
    <div class = "buttons">
      <%= f.button class: "special-button" %>
      <%=link_to 'Cancel', user_recipes_path%>
    </div>
<% end %>